inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 11

training:
    task: seq_rec_linear
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 20001
    curriculum:
        dims:
            start: 20
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 11
            inc: 2
            interval: 2000

out_dir: ../models/seq_rec_linear

wandb:
    name: "seq_rec_linear"
